import pyzx as zx

import sys
import os

import matplotlib.pyplot as plt

# 1. Point Python to the folder containing the file
sys.path.append(os.path.abspath("/home/benne/Circopt-RL-ZXCalc/rl-zx/gym-zx/gym_zx/envs"))
from zx_env import ZXEnv

from qiskit import QuantumCircuit

import qiskit.qasm2 as qasm2

# qiskit_circ = QuantumCircuit(2)

# qiskit_circ.h(0)
# qiskit_circ.cx(0,1)


# print(qiskit_circ)

qiskit_circ = QuantumCircuit(3)
qiskit_circ.h(0)
qiskit_circ.cx(0, 1)
qiskit_circ.h(0)
qiskit_circ.h(1)
qiskit_circ.cx(1, 2)
qiskit_circ.cx(0, 1)
qiskit_circ.h(1)

print(qiskit_circ)


qasm_string = qasm2.dumps(qiskit_circ)

circuit = zx.Circuit.from_qasm(qasm_string)

custom_circuit = circuit

qubits = circuit.qubits
depth = circuit.depth()
graph_zxdd = custom_circuit.to_graph()
tikz_graph = graph_zxdd.to_tikz()
print(tikz_graph)

env = ZXEnv(
    qubits=qubits, 
    depth=depth, 
    circuit=circuit, 
    rand_circ=False # Ensure it uses your circuit instead of generating a random one
)
env.device = "cpu"

obs, info = env.reset_with_custom_circuit(custom_circuit=custom_circuit)

current_graph = env.graph 

tikz_code = current_graph.to_tikz()

#print("\n--- COPY & PASTE THIS TIKZ CODE INTO OVERLEAF ---")
#print(tikz_code)


# --- Continuing from your script ---
# 1. Inspect the available actions generated by reset_with_custom_circuit
print("Available Pivots:", env.pivot_info_dict)
print("Available Gadget Fusions:", env.gadget_fusion_ids)

# 2. Extract an action ID from the policy observation space
# (The policy_obs() method structures the graph and valid action nodes for a GNN)
x, edge_index, edge_features, identifier = env.policy_obs()

# For a quick manual test, let's select the "STOP" action token 
# encoded by the environment's internal dimensions:
stop_action = int(env.shape * (env.shape + 1) + 1)

# 3. Pass the action to the step method
next_graph, reward, done, truncated, info = env.step(stop_action)

print(f"Step executed. Reward: {reward}, Done: {done}")
print("Final Circuit Stats:", info.get("rl_stats"))



current_graph = env.graph 

tikz_code = current_graph.to_tikz()

#print("\n--- COPY & PASTE THIS TIKZ CODE INTO OVERLEAF ---")
#print(tikz_code)



